using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TigerCompiler.AST
{
    enum TigerTokenTypes
    {
        ALIAS_DECL = 4,
        AND = 5,
        ARRAY = 6,
        ARRAY_CREATION = 7,
        ARRAY_TYPE_DECL = 8,
        ASCII_ESC = 9,
        ASSIGN = 10,
        AT = 11,
        BREAK = 12,
        COLON = 13,
        COMMA = 14,
        COMMENT = 15,
        DIV = 16,
        DO = 17,
        DOT = 18,
        ELSE = 19,
        END = 20,
        EQUAL = 21,
        ESC_SEQ = 22,
        EXPRESSION_LIST = 23,
        EXPRESSION_SEQ = 24,
        FOR = 25,
        FUNCTION = 26,
        FUNCTION_CALL = 27,
        FUNCTION_DECL = 28,
        GT = 29,
        GT_EQUAL = 30,
        ID = 31,
        IF = 32,
        IF_THEN = 33,
        IF_THEN_ELSE = 34,
        IN = 35,
        INT = 36,
        LBRACE = 37,
        LBRACKET = 38,
        LET = 39,
        LPAR = 40,
        LT = 41,
        LT_EQUAL = 42,
        MINUS = 43,
        MUL = 44,
        NIL = 45,
        NON_EQUAL = 46,
        OF = 47,
        OR = 48,
        PLUS = 49,
        PRINTABLE_CHARACTER = 50,
        PROGRAM = 51,
        RBRACE = 52,
        RBRACKET = 53,
        RECORD_CREATION = 54,
        RECORD_DECL = 55,
        RPAR = 56,
        SEMICOLON = 57,
        STRING = 58,
        THEN = 59,
        TO = 60,
        TYPE = 61,
        TYPE_DECL = 62,
        TYPE_ID = 63,
        UMINUS = 64,
        VAR = 65,
        VAR_DECL = 66,
        WHILE = 67,
        WS = 68
    }
}
